{% set name = "multisheller" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/multisheller/archive/{{ version }}.tar.gz
  sha256: e7f5be312cdf54d00d8ac12f63eebd77915430da41ce59f3823c0c228963278d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - multisheller = multisheller.cli.main:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - multisheller
  source_files:
    - test/*
  requires:
    - pytest
    - zsh               # [unix]
    - xonsh
    - python {{ python_min }}
  commands:
    - multisheller -h
    - pytest test/

about:
  home: https://github.com/wolfv/multisheller
  license: BSD-3-Clause
  license_file: LICENSE
  summary: This project implements a simple DSL (in Python) to generate shell scripts for many different shells.
  dev_url: https://github.com/wolfv/multisheller

extra:
  recipe-maintainers:
    - wolfv
    - traversaro
