{% set name = "multisheller" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wolfv/multisheller/archive/{{ version }}.tar.gz
  sha256: 5ed9a971576e1ba37d6f360e94f1e5abdbebac9e42534af68e2be8b2e7fb3efb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - multisheller = multisheller.cli.main:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - multisheller
  source_files:
    - test/*
  requires:
    - pytest
    - zsh               # [unix]
    - xonsh
  commands:
    - multisheller -h
    - pytest test/

about:
  home: https://github.com/wolfv/multisheller
  license: BSD-3-Clause
  license_file: LICENSE
  summary: This project implements a simple DSL (in Python) to generate shell scripts for many different shells.
  dev_url: https://github.com/wolfv/multisheller

extra:
  recipe-maintainers:
    - wolfv
    - traversaro
